# Generated by Django 6.0 on 2026-01-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_on_vacation',
            field=models.BooleanField(default=False),
        ),
    ]
